name: Unit Tests

on: [ push ]

jobs:
  tests:
    name: Unit Tests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php: [ '7.4', '8.0', '8.1' ]

    steps:
      - uses: actions/checkout@v3

      - uses: php-actions/composer@v6
        with:
          php_version: "${{ matrix.php }}"

      - name: PHPUnit (php-actions)
        uses: php-actions/phpunit@v3
        with:
          php_extensions: xdebug
          php_version: "${{ matrix.php }}"
          args: --coverage-text
        env:
          XDEBUG_MODE: coverage
