name: Unit Tests

on: [ push ]

jobs:
  tests:
    name: Unit Tests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php: [ '7.4', '8.0', '8.1', '8.2' ]

    steps:
      - uses: actions/checkout@v4

      - uses: php-actions/composer@v6
        with:
          php_version: "${{ matrix.php }}"

      - name: Parse PHPUnit version
        run: echo "PHPUNIT_VERSION=$(composer show phpunit/phpunit --no-interaction --format json | jq -r .versions[0])" >> $GITHUB_ENV

      - name: PHPUnit (php-actions)
        uses: php-actions/phpunit@v3
        with:
          version: ${{ env.PHPUNIT_VERSION }}
          php_extensions: xdebug
          php_version: "${{ matrix.php }}"
          args: --coverage-text
        env:
          XDEBUG_MODE: coverage
